export type TripType = 'One Way' | 'Round Trip' | 'Multi-City';
export interface FlightSearchData { origin?: string | null; destination?: string | null; tripType?: TripType; cabin?: string; departureDateOffsetDays?: number; returnDateOffsetDays?: number; adults?: number; children?: number; infants?: number; originSearch?: string; destinationSearch?: string; expectedSuggestionFields?: string[]; selectionRequired?: boolean; pastDateOffsetDays?: number; currentDateOffsetDays?: number; futureDateOffsetDays?: number; defaultCabin?: string; cabinOptions?: string[]; minimum?: PassengerCounts; incremented?: PassengerCounts; ageLabels?: Record<string, string>; initialSegmentCount?: number; maximumSegmentCount?: number; segments?: FlightSegment[]; attemptedSeventhSegment?: FlightSegment; }
export interface FlightSegment { origin: string; destination: string; departureDateOffsetDays: number; }
export interface PassengerCounts { adults: number; children: number; infants: number; }
export interface ValidationSecurityData { origin?: string | null; destination?: string | null; tripType?: TripType; departureDateOffsetDays?: number; adults?: number; children?: number; infants?: number; outboundDateOffsetDays?: number; missingReturn?: null; earlierReturnDateOffsetDays?: number; validReturnDateOffsetDays?: number; parameter?: string; value?: string; payloads?: string[]; targetControls?: string[]; }
export interface Dataset<T> { datasetId: string; relatedTestCase: string; dataCategory: string; description: string; inputData: T; expectedOutcome: string; }
export interface ResultData { airline: string; flightNumber: string; departureAirport: string; arrivalAirport: string; departureDateOffsetDays: number; departureTime: string; arrivalTime: string; durationMinutes: number; stops: number; currency: string; cabin: string; baggage: string; }
export interface ResultRefinementData { sortOptions: string[]; filterTypes: string[]; pageSizes: number[]; clearFilters: boolean; minimumResultCountForPagination: number; }
export interface IntegrationData { successState?: { supplierStatus: string; resultCount: string }; unavailableState?: { supplierStatus: string; resultCount: number }; livePriceClaim?: boolean; search?: FlightSearchData; selectedResult?: { flightNumber: string; fare: string; baggage: string }; paymentData?: string; }
export interface ResultMutation { parameter: string; value: string; }
